version: '3'
services:
  mysql:
    image: mysql:8.0.39
    container_name: phone-shop-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: phone-shop-backend
    environment:
      DB_HOST: mysql
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mysql
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: phone-shop-frontend
    depends_on:
      - backend
    ports:
      - "8082:8080"

volumes:
  mysql_data: